### ISSUE TITLE
how to get date mask 

### ISSUE THREAD

**Issue by Victor1506** [artemkrachulov/AKMaskField#12]
how to get date mask in "yyyy-mm-dd" format?

**Comment by artemkrachulov** [comment]
mask : {dddd}-{dd}-{dd}
maskTemplate : yyyy-mm-dd

Thx,
Artem

**Comment by Victor1506** [comment]
how can i do 12 month limit? 
or 30 days limit?

**Comment by artemkrachulov** [comment]
New version supported separate blocks editing. You can check block text and output filtered text.

**Comment by Gustavopcaiafa** [comment]
@artemkrachulov How can i do that? I can find the block index and see how many elements there are in it, but can`t see the text it contains.
