### ISSUE TITLE
How to get original text from maskField

### ISSUE THREAD

**Issue by haydarKarkin** [artemkrachulov/AKMaskField#2]
Hello,

I made a mask like as ({ddd}) {ddd}-{dddd}; howerver, I need to get it like as dddddddddd for my url. How can I do it?

Thanks,

Haydar

**Comment by artemkrachulov** [comment]
Hi, thx for using plugin. Your solution:

```swift
var template: String = ""
for block in self.field.maskObject {
    template += block.template
}

println("Template text: \(template)")
```

Best, 
Artem

**Comment by haydarKarkin** [comment]
Hi Artem,

Thank you very much for your help.

Best regards,
Haydar
