### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by viniciusvieir** [artemkrachulov/AKMaskField#21]
Any plans to support Swift 3.0?

**Comment by lfarah** [comment]
Would also love to use AKMaskField in Xcode 8

**Comment by YurchukV** [comment]
How soon appear Support Swift 3?

**Comment by artemkrachulov** [comment]
Support Swift 3

**Comment by lfarah** [comment]
Thanks, @artemkrachulov! 🎉 🎉 🎉
