### ISSUE TITLE
maskDelegate is inaccessible

### ISSUE THREAD

**Issue by jeremypiednoel** [artemkrachulov/AKMaskField#24]
Hi I try to trigger the `.ValueChanged` on AKMaskField but as soon as i set `maskExpression` the event is not trigger anymore. therefore i tried to set the delegate and i have this error

`'maskDelegate' is inaccessible due to 'internal' protection level`

```swift
valueField.maskDelegate = self
valueField.text = value
```

I use the swift3 branch.

Thanks,
Have a good day.

**Comment by ursanotsomajor** [comment]
Have the same issue as the jeremypiednoel.

**Comment by victoraugustolls** [comment]
Same problem here

**Comment by artemkrachulov** [comment]
Hi. Thx for finding this issue. To help me fix this problem I need fully stimulate your situation. Can you help me with this and past code which leads to an error?

**Comment by ursanotsomajor** [comment]
@artemkrachulov Hello! I'll answer for jeremypiednoel:

**Comment by jeremypiednoel** [comment]
Thanks @ursanotsomajor , indeed i removed the code from my project. so i wasn't able to show you.

**Comment by road-t** [comment]
I have the same issue after migrating to Swift 3
The same is for maskStatus.
cleanText is absent at all((

**Comment by artemkrachulov** [comment]
Fixed
