### ISSUE TITLE
crash on backspace all chars

### ISSUE THREAD

**Issue by shadrus** [artemkrachulov/AKMaskField#5]
private func moveCaretToPosition(position: Int) {
    
        if let beginningOfDocument: UITextPosition = beginningOfDocument {
            
            let caretPosition = positionFromPosition(beginningOfDocument, offset: position)
            selectedTextRange  = textRangeFromPosition(caretPosition!, toPosition: caretPosition!)
        }
    }

was changed for

if let caretPosition = positionFromPosition(beginningOfDocument, offset: position){
                selectedTextRange  = textRangeFromPosition(caretPosition, toPosition: caretPosition)
            }

**Comment by artemkrachulov** [comment]
Hi, check new version, please
