### ISSUE TITLE
mask isn't automatically applied if text is programmatically set

### ISSUE THREAD

**Issue by sabernar** [artemkrachulov/AKMaskField#7]
If you put the following line into the Demo's viewDidLoad code, it does not autoformat the text.

        card.text = "1234123412341234"

Is there a way to force it to trigger the mask?

**Comment by AccentureAPinto** [comment]
The mask seems to be applyed only if text is set on viewDidAppear. I found a workaround to force it in viewDidLoad:
`
card.textField(card, shouldChangeCharactersInRange: NSMakeRange(0, 0), replacementString: "1234123412341234")
`

**Comment by artemkrachulov** [comment]
Hi, check new version, please
